# Generated by Django 5.1.5 on 2025-01-21 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobWagon', '0003_alter_booking_contact_alter_booking_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='booking',
            new_name='Bookingdb',
        ),
    ]
