# Generated by Django 5.1.5 on 2025-01-21 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobWagon', '0004_rename_booking_bookingdb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookingdb',
            new_name='Booking',
        ),
    ]
