# Generated by Django 5.1.5 on 2025-01-21 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobWagon', '0005_rename_bookingdb_booking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='Bookings',
        ),
    ]
