# Generated by Django 5.1.5 on 2025-01-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobWagon', '0008_booking_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('purpose', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('hours', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Booking_page',
        ),
        migrations.DeleteModel(
            name='Bookingdb',
        ),
    ]
