# Generated by Django 5.1.5 on 2025-01-21 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobWagon', '0012_bookings_delete_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='contact',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='location',
        ),
    ]
