# Generated by Django 5.1.5 on 2025-01-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobWagon', '0014_bookings_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
