# Generated by Django 5.1.5 on 2025-01-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobWagon', '0018_alter_bookings_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='partner_status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10),
        ),
    ]
