# Generated by Django 5.1.5 on 2025-01-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobWagon', '0019_bookings_partner_status_alter_bookings_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='reason',
            field=models.TextField(blank=True, default='Pending', null=True),
        ),
    ]
