# Generated by Django 5.1.5 on 2025-01-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobWagon', '0020_alter_bookings_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='reason',
            field=models.TextField(blank=True, default='Verifying Your Details', null=True),
        ),
    ]
